### ISSUE TITLE
Adding proxy support.

### ISSUE THREAD

**Issue by mrogelja** [excelwebzone/EWZRecaptchaBundle#1]
Could you add proxy support in validation ? That requires to implement a fopen with stream context option or curl connection.

Suggestion from [GaretJax/phpbrowscap] [1] source code.

[1]: https://github.com/GaretJax/phpbrowscap/blob/master/src/phpbrowscap/Browscap.php#L337

**Comment by sterrien** [comment]
I'm interested too.
But the MR is a bit outdated. I will do it from the current master branch.

**Comment by sterrien** [comment]
Thanks a lot !
