### ISSUE TITLE
Symfony 2.8 deprecation.

### ISSUE THREAD

**Issue by jorismulliez** [excelwebzone/EWZRecaptchaBundle#113]
Hi all,

Since I'm trying to use this bundle, I see some deprecation in my forms.

>  	Accessing type "form" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\FormType" instead.

and

> EWZ\Bundle\RecaptchaBundle\Form\Type\RecaptchaType: The FormTypeInterface::getName() method is deprecated since version 2.8 and will be removed in 3.0. Remove it from your classes. Use getBlockPrefix() if you want to customize the template block prefix. This method will be added to the FormTypeInterface with Symfony 3.0.

Can you check this problem ?
I'm in version 1.4

Thanks,

**Comment by OskarStark** [comment]
this is just an information and no error, are you willing to privide a PR?

**Comment by cilefen** [comment]
These seem gone on the master branch of this bundle. Can anyone confirm

**Comment by cilefen** [comment]
This looks like it was fixed in master, from commit 0a5b8b061165a298113962a5fd88eb05b485287d. I recommend closing this.
