### ISSUE TITLE
Tag a new release for 1.4 for Symfony 2.8

### ISSUE THREAD

**Issue by usmanzafar** [excelwebzone/EWZRecaptchaBundle#120]
Hey guys, it seems like  since tag >= 1.4.2 none of them are compatible with symfony 2.8. It directly switches to "~3.0". May i ask for suggestion on what tag we should refer to if we want to use  >= 1.4.2 on symfony 2.8 and avoid the "FormTypeInterface::getName() method deprecated" notice at the same time.

Previous issues discussed the same and the same is in master as well but does not appear in tag release. #113

**Comment by excelwebzone** [comment]
Added new tag 1.4.4
