### ISSUE TITLE
Is not required in my form

### ISSUE THREAD

**Issue by juanjo19** [excelwebzone/EWZRecaptchaBundle#125]
i need that my captcha will be required in my form.

**Comment by excelwebzone** [comment]
```php
$builder->add('recaptcha', EWZRecaptchaType::class, array(
	// ...
    'required' => true
));
```

**Comment by juanjo19** [comment]
only with this attribute not function. :( help!

**Comment by juanjo19** [comment]
my problem is, I have a global form but he isn't a twig form but my captcha if is a twig form. some help?
