### ISSUE TITLE
I'm not a robot checkbox

### ISSUE THREAD

**Issue by Soggard** [excelwebzone/EWZRecaptchaBundle#130]
I installed this bundle, but I was expecting to have the "I'm not a robot" checkbox. Isn't it possible to use the new checkbox recaptcha, instead of the old one ?

Thanks !

**Comment by mablae** [comment]
It is.

**Comment by Soggard** [comment]
Is there something to configure to get the new one ? Have I done something wrong ?

**Comment by mablae** [comment]
@Soggard  Maybe your are including old Javascript that interfers with the new reCaptcha stuff? Are you migrating from an existent solution? 

I never had such issues. I think this bundle does only implement the new "I am not a robot" widget. Is this correct, @excelwebzone ?

**Comment by excelwebzone** [comment]
Correct.

**Comment by Soggard** [comment]
It seems that the problem was from the API. I was working on a VM, and google couldn't recognize my domain name.
I disabled the DN checking on the API, now it works, thank you :)
