### ISSUE TITLE
EWZRecaptchaBundle.php need to be moved in "src" directory

### ISSUE THREAD

**Issue by maisoui** [excelwebzone/EWZRecaptchaBundle#141]
Hi,

Since the last changes, I have error in the AppKernel.php file. I noticed that you created a "src" directory, and you updated the composer.json. I think you need to move the EWZRecaptchaBundle.php inside this "src" directory.

Best regards

**Comment by progrupa** [comment]
Seriously, that's a really silly mistake to make...

**Comment by excelwebzone** [comment]
Fixed!

**Comment by progrupa** [comment]
Well, props for a quick response :)
