### ISSUE TITLE
Support for Google invisible reCAPTCHA

### ISSUE THREAD

**Issue by crmpicco** [excelwebzone/EWZRecaptchaBundle#147]
Hi,

Do you have any plans in the pipeline to support Google's new invisible reCAPTCHA?

https://www.google.com/recaptcha/intro/comingsoon/invisible.html

Many thanks.

**Comment by PouleR** [comment]
Is this something the bundle has to implement or is it enough to create a new (Invisible) reCAPTCHA with new keys ?

**Comment by lordjancso** [comment]
I've tried in by changing the keys, but it was not enough, so it needs a little code update.

**Comment by PouleR** [comment]
After reading the docs (https://developers.google.com/recaptcha/docs/invisible#programmatic_execute), I found out that you can set the 'size' option to 'invisible.

For example in your formbuilder:

`        $builder->add('recaptcha', EWZRecaptchaType::class, array(
            'attr' => array(
                'options' => array(
                    'theme' => 'light',
                    'type' => 'image',
                    'size'  => 'invisible',
                    ),
                ),`

**Comment by crmpicco** [comment]
@PouleR It looks like it needs more work than just setting the size to 'invisible'.

**Comment by crmpicco** [comment]
I'm taking a run at this just now. If I can contribute to the project then I will submit a PR (assuming you accept PRs)

**Comment by jonathanbull** [comment]
Looking forward to seeing this @crmpicco, didn't get too far myself!

**Comment by crmpicco** [comment]
@jonathanbull I've submitted a PR for this https://github.com/excelwebzone/EWZRecaptchaBundle/pull/154. So hopefully it's something that the project maintainers are looking for...
