### ISSUE TITLE
Failed to update v1.4.4 => v1.4.5

### ISSUE THREAD

**Issue by zablik** [excelwebzone/EWZRecaptchaBundle#149]
I have an error trying to update dependency. What can be wrong?

composer.json:
....
"excelwebzone/recaptcha-bundle": "^1.4",
....

I use Vagrant with vagrant-nfs plugin on Windows host

**$ composer install**
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 0 installs, 1 update, 0 removals
  - Updating excelwebzone/recaptcha-bundle (v1.4.4 => v1.4.5) Downloading: 100%    **Update failed (Could not delete /var/www/myproject/vendor/excelwebzone/recaptcha-bundle/.nfs00000000000244f000000023: )
    Would you like to try reinstalling the package instead [yes]?**
  - Removing excelwebzone/recaptcha-bundle (v1.4.4)
  - Installing excelwebzone/recaptcha-bundle (v1.4.5) Downloading: 100%    **Failed to download excelwebzone/recaptcha-bundle from dist: Could not delete /var/www/myproject/vendor/excelwebzone/recaptcha-bundle/.nfs000000000002452d00000024:
    Now trying to download from source**
  - Installing excelwebzone/recaptcha-bundle (v1.4.5) Cloning c26cc2fa93

  [RuntimeException]
  Failed to execute git checkout 'c26cc2fa93649c05d9e1d2fc7130df16d86b4f13' -- && git reset --hard 'c26cc2fa93649c05d9e1d2fc7130df16d86b4f13' --
  error: The following untracked working tree files would be overwritten by checkout:
        .editorconfig
        .gitignore
        .travis.yml
        LICENSE
        README.md
        Tests/Form/Type/EWZRecaptchaTypeTest.php
        Tests/Locale/LocaleResolverTest.php
        composer.json
        phpunit.xml.dist
        src/Bridge/Form/Extension/RecaptchaExtension.php
        src/Bridge/README.md
        src/Bridge/RecaptchaServiceProvider.php
        src/DependencyInjection/Configuration.php
        src/DependencyInjection/EWZRecaptchaExtension.php
        src/EWZRecaptchaBundle.php
        src/Form/Type/EWZRecaptchaType.php
        src/Locale/LocaleResolver.php
        src/Resources/config/services.yml
        src/Resources/translations/validators.bg.xlf
        src/Resources/translations/validators.ca.xlf
        src/Resources/translations/validators.cs.xlf
        src/Resources/translations/validators.de.xlf
        src/Resources/translations/validators.en.xlf
        src/Resources/translations/validators.es.xlf
        src/Resources/translations/validators.fr.xlf
        src/Resources/translations/validators.nl.xlf
        src/Resources/translations/validators.pl.xlf
        src/Resources/translations/validators.ro.xlf
        src/Resources/translations/validators.ru.xlf
        src/Resources/translations/validators.sk.xlf
        src/Resources/translations/validators.tr.xlf
        src/Resources/translations/validators.uk.xlf
        src/Resources/views/Form/ewz_recaptcha_widget.html.php
        src/Resources/views/Form/ewz_recaptcha_widget.html.twig
        src/Validator/Constraints/IsTrue.php
        src/Validator/Constraints/IsTrueValidator.php
  Please move or remove them before you can switch branches.
  Aborting

**Comment by excelwebzone** [comment]
Try removing it manually, then reinstall it.
