### ISSUE TITLE
please use semver

### ISSUE THREAD

**Issue by zkiiito** [excelwebzone/EWZRecaptchaBundle#150]
we've just upgraded a patch version (1.4.1 to 1.4.5) and were surprised that the main class name was changed, which is obviously a BC break. 
could you please use semver, or at least maintain the change log reflecting breaking changes?

thanks!

**Comment by excelwebzone** [comment]
I updated the 1.4.5 release tag with the files relocation (into the `src` folder)

**Comment by zkiiito** [comment]
as I learned more about our issue, relocation was not a problem - it's handled by composer - but the class renaming, which happened in 1.4.2

**Comment by excelwebzone** [comment]
Added a note to 1.4.2 about it.
