### ISSUE TITLE
This value is not a valid captcha: error in prod but not in local 

### ISSUE THREAD

**Issue by thibaultfalque** [excelwebzone/EWZRecaptchaBundle#158]
Hi, 

I have a really strange problem. The captcha works on one page but not on two other pages, or it says "This value is not a valid captcha.", While I do exactly the same thing, and the problem only occurs from my server and not When I'm in local execution ...

I am under the latest version of symfony. My server is an Elastik Beanstealk server at Amazon.

This form works: https://aws.fitjiva.com/register/

and this not: https://aws.fitjiva.com/registerpro/

Any idea? 

Thanks in advance.

**Comment by everio** [comment]
Have you found a solution ?

**Comment by ovidiul** [comment]
Same issue here, any suggestions?

**Comment by HamHamFonFon** [comment]
Same problem in preprod environnement.

**Comment by Constant23** [comment]
I fixed this problem by enabling allow_url_fopen and disabling disable_functions in php

**Comment by Dark-reaper** [comment]
> I fixed this problem by enabling allow_url_fopen and disabling disable_functions in php

This worked for me too !
