### ISSUE TITLE
Badge position

### ISSUE THREAD

**Issue by jakenoble** [excelwebzone/EWZRecaptchaBundle#164]
Is there a way to position the badge as documented on https://developers.google.com/recaptcha/docs/invisible

I have tried many different ways but nothing works.

**Comment by Andyhutchings** [comment]
For any one else with this issue. You can overwrite the form theme template to include more data-attributes.

Create `app/Resources/EWZRecaptchaBundle/views/Form/ewz_recaptcha_widget.html.twig` and copy the contents of the same file from the bundle.

Changed the div that includes all the google recapcha data attribute settings to the following.

```
   <div class="g-recaptcha"
       data-sitekey="{{ form.vars.public_key }}"

       {% for dataAttr, dataValue in attr.options %}
             data-{{ dataAttr }}="{{ dataValue }}"
       {% endfor %}
   ></div>
```

You can then just add new options to the from field e.g

```
 $builder
      ->add('username', TextType::class)
      ->add('plainPassword', PasswordType::class)
      ->add('recaptcha', EWZRecaptchaType::class, array(
                'mapped' => false,
                'constraints' => array(new RecaptchaTrue()),
                'attr' => array(
                    'options' => array(
                        'theme' => 'light',
                        'type'  => 'image',
                        'size' => 'invisible',
                        'defer' => true,
                        'async' => true,
                        'callback' => 'onLoginFormSubmit',
                        'bind' => 'loginButton',
                        'badge' => 'inline '
                    )
                )
            ));
```

**Comment by miisieq** [comment]
Why we can't just add this option to the form (`EWZRecaptchaType`)?
