### ISSUE TITLE
Version 1.5.2 with dependency from SecurityBundle

### ISSUE THREAD

**Issue by faelgabriel** [excelwebzone/EWZRecaptchaBundle#193]
On 1.5.2 version was added a dependency injection of a service from SecurityBundle, but in some applications I do not load that bundle in my kernel.

Can that dependency be injected optionally? Or something like to only inject that dependency if SecurityBundle was loaded.

**Comment by excelwebzone** [comment]
I updated the composer.json to auto load "symfony/security", and create v.1.5.3.

**Comment by faelgabriel** [comment]
@excelwebzone I keep having the problem because I do not register the SecurityBundle in AppKernel.php (and I do not use that): `new Symfony\Bundle\SecurityBundle\SecurityBundle()`
To me keep using EWZRecaptchaBundle, should I register SecutiryBundle in my kernel even I do not use that? This does not seem to be flexible.

I think the SecurityBundle comes with symfony/symfony components, so we do not need to include the requirement on composer.json.

**Comment by excelwebzone** [comment]
@faelgabriel try now with this fix.. and if good I will bump to a new version..

**Comment by faelgabriel** [comment]
@excelwebzone Yeah, it worked now.

**Comment by excelwebzone** [comment]
Cool. Create a new release v1.5.4

**Comment by faelgabriel** [comment]
@excelwebzone Thanks for your help and for the quick fix.
