### ISSUE TITLE
[Symfony 4.2] Twig failed to render the widget

### ISSUE THREAD

**Issue by IgorTimoshenko** [excelwebzone/EWZRecaptchaBundle#226]
Hi!

I'm updating a project from Symfony 4.1 to Symfony 4.2 and I'm faced with a problem.

Twig can't render the widget and outputs the following:

> An exception has been thrown during the rendering of a template ("Notice: Array to string conversion").

The last step in the traceback refers to https://github.com/symfony/twig-bridge/blob/v4.2.7/Resources/views/Form/form_div_layout.html.twig#L432.

It looks like the issue in the form type options. The `attr` option contains the `options` key which is an array (the `attr` option is an associative array with HTML attributes as keys accordingly to the Symfony [docs](https://symfony.com/doc/current/reference/forms/types/form.html#attr)).

Please fix this issue.

Cheers!

**Comment by guzzlefry** [comment]
This is still an issue with version 1.5.15 on Symfony 4.3.x.

**Comment by sonofliberty** [comment]
@IgorTimoshenko Did you manage to fix this issue in your project? I'm having the same problem.

**Comment by icedevelopment** [comment]
@see https://github.com/excelwebzone/EWZRecaptchaBundle/issues/234#issuecomment-1098792678
