### ISSUE TITLE
W3C validation

### ISSUE THREAD

**Issue by lobodol** [excelwebzone/EWZRecaptchaBundle#229]
Hello,
I'm using this great bundle on my website but when I trigger the [W3C Markup Validation](https://validator.w3.org/), I've got 2 errors:

* The frameborder attribute on the iframe element is obsolete. Use CSS instead.
* The scrolling attribute on the iframe element is obsolete. Use CSS instead.

The "scrolling" & "frameborder" attributes are [not supported in HTML5](https://www.w3schools.com/tags/tag_iframe.asp) so, my question is why keep them?
Are they kept for kind of retrocompatibility?

Looking forward to reading you

**Comment by JohJohan** [comment]
Hi, i just started working with this bundle today but is this not added by Google Recaptcha itself? If i look for `frameborder` in this repository i cannot find any results

**Comment by lobodol** [comment]
When I started this issue I was using v1.5.11 of this bundle which included attributes `frameborder` in its templates: https://github.com/excelwebzone/EWZRecaptchaBundle/blob/v1.5.11/src/Resources/views/Form/ewz_recaptcha_widget.html.php

Since, I updated to version 1.5.21 where attributes `frameborder` have been removed.

I guess we can close this issue.
