### ISSUE TITLE
BC on 1.5.23 with php5.6 and symfony 2.8

### ISSUE THREAD

**Issue by stevro** [excelwebzone/EWZRecaptchaBundle#257]
The commit: https://github.com/excelwebzone/EWZRecaptchaBundle/commit/0240aab8db69d1681832fd6b394edc3656c15e3c

The error:
The service "ewz_recaptcha.form_builder_factory" has a dependency on a non-existent service "symfony\component\form\formfactoryinterface".

**Comment by excelwebzone** [comment]
See https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/FormFactoryInterface.php

**Comment by stevro** [comment]
@excelwebzone , it works if autowiring is enabled :), my project was started on sf 2.4 and got updated only to 2.8 without service definition updates.
https://symfony.com/doc/2.8/service_container/autowiring.html
