### ISSUE TITLE
Key "ewz_recaptcha_hide_badge" ... does not exist

### ISSUE THREAD

**Issue by maddy2101** [excelwebzone/EWZRecaptchaBundle#260]
symfony 4.4, excelwebzone/recaptcha-bundle 1.5.24, recaptcha V3
dev setting: ewz_recaptcha.enabled = false

=> Key "ewz_recaptcha_hide_badge" for array with keys "value, attr, form, id, name, full_name, disabled, label, label_format, multipart, block_prefixes, unique_block_prefix, row_attr, translation_domain, label_translation_parameters, attr_translation_parameters, cache_key, errors, valid, data, required, size, label_attr, help, help_attr, help_html, help_translation_parameters, compound, method, action, submitted, ewz_recaptcha_enabled, ewz_recaptcha_api_host, ewz_recaptcha_api_uri, public_key" does not exist.

This ist due to AbstractEWZRecaptchaType->buildView() returns an empty array in line 64 for a disabled captcha.
The missing key would be set in the method call addCustomVars(), that is in line 68 (mind it, after the return). So the key is not set and then the twig template resolve throws the error.

**Comment by nithiz** [comment]
This does mean we can't test the widget in development anymore?

**Comment by sovetski** [comment]
I am getting the same error on Symfony 6, why this issue is closed without any explanation? @excelwebzone

**Comment by vasilvestre** [comment]
Also interested into this, I can't debug my issue now
