### ISSUE TITLE
Php8 support

### ISSUE THREAD

**Issue by VincentLanglet** [excelwebzone/EWZRecaptchaBundle#268]
Hi @excelwebzone, is it possible to support php 8 ?

I saw this PR working on it https://github.com/excelwebzone/EWZRecaptchaBundle/pull/267

**Comment by excelwebzone** [comment]
Unfortunately, upgrading to PHP8 will required large code change. The PR you referring too, can' tbe merged - If @pbories will fix it I will merge change.

**Comment by VincentLanglet** [comment]
Then the issue should stay open until the php8 support is added.

What do you mean `large code change` ?
Seems like @pbories was needed an answer about what to do this the tests.
Php8 is supported by PhpUnit >= 8 which require to add return type `: void` to `setUp` method ; doing this change need to restrict the php version of the ci to 7.1+.

**Comment by excelwebzone** [comment]
I guess so..
