### ISSUE TITLE
Add some options in the form builder

### ISSUE THREAD

**Issue by victormartin** [excelwebzone/EWZRecaptchaBundle#27]
Is it possible to add more options like "enable" or "secure" in the ewz_recaptcha element inside the buildForm function? For example:

public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('recaptcha', 'ewz_recaptcha', array(
        'attr' => array(
            'options' => array(
                // other options like theme, lang and custom_translations
                'secure' => true, // the new option
            ),
        ),
        'mapped' => false,
        // constraints and more
    ));
}

And then in the RecaptchaType file, it could be like this:

public function buildView(FormView $view, FormInterface $form, array $options)
{
    $view->vars = array_replace($view->vars, array(
        'ewz_recaptcha_enabled' => $this->enabled,
    ));

    if (!$this->enabled) {
        return;
    }

    /* New code */
    if (isset($options['attr'])) {
        $attr = $options['attr'];

        if (isset($attr['options']) && !is_null($attr['options'])) {
            $options = $attr['options'];

            if (isset($options['secure'])) {
                $this->secure = $options['secure'];
            }
        }
    }
    /* End code */

    if ($this->secure) {
        $server = self::RECAPTCHA_API_SECURE_SERVER;
    } else {
        $server = self::RECAPTCHA_API_SERVER;
    }

    $view->vars = array_replace($view->vars, array(
        'url_challenge' => sprintf('%s/challenge?k=%s', $server, $this->publicKey),
        'url_noscript'  => sprintf('%s/noscript?k=%s', $server, $this->publicKey),
        'public_key'    => $this->publicKey,
    ));
}

Thank you

**Comment by excelwebzone** [comment]
You can always extend the class on you own project and add the options you need.
