### ISSUE TITLE
Bug getting language

### ISSUE THREAD

**Issue by victormartin** [excelwebzone/EWZRecaptchaBundle#28]
On RecaptchaType.php, change the constructor to:

    public function __construct(ContainerInterface $container)
    {
        $this->publicKey = $container->getParameter('ewz_recaptcha.public_key');
        $this->secure    = $container->getParameter('ewz_recaptcha.secure');
        $this->enabled   = $container->getParameter('ewz_recaptcha.enabled');
        $this->language  = $container->getParameter('ewz_recaptcha.locale_key');
    }

**Comment by excelwebzone** [comment]
Fixed!
