### ISSUE TITLE
Wrong path for recaptcha.css

### ISSUE THREAD

**Issue by gvioss** [excelwebzone/EWZRecaptchaBundle#282]
Hi,

I'm using the bundle in 1.5.31 and I notice that the path of the `recaptcha.css` in `src/Resources/views/Form/v3/ewz_recaptcha_widget.html.twig` is `/bundles/ewz_recaptcha/css/recaptcha.css` but when generating assets in my Symfony project (with assets:install command), the path to the file is `/bundles/ewzrecaptcha/css/recaptcha.css` without the _ between ewz and recaptcha.

Regrads

**Comment by stingus** [comment]
Yes, same issue here

**Comment by stingus** [comment]
This should be easily fixed here `src/Resources/views/Form/v3/ewz_recaptcha_widget.html.twig`.
