### ISSUE TITLE
I don't want to use Formbuilder

### ISSUE THREAD

**Issue by Sshuichi** [excelwebzone/EWZRecaptchaBundle#29]
Hello , I want to display the captcha directly from twig or calling the value from my controller and display it on my twig file. I have never used FormBuilder and I do not want to use it now.
Can you help ?

**Comment by lethak** [comment]
The bundle is optimized to work with a FormType/Builder/Validator combo.
In my point of view, there is no point using it if you do not plan to use a FormBuilder.
