### ISSUE TITLE
Remove the customisation and ajax

### ISSUE THREAD

**Issue by adityapatadia** [excelwebzone/EWZRecaptchaBundle#33]
As the new google captcha does not support customisation we should remove the documentation and support for the same from this bundle. Apart from that, ajax option has also lost relevance so it should be removed. Let me know your views @excelwebzone

**Comment by adityapatadia** [comment]
Any idea about this?

**Comment by excelwebzone** [comment]
@adityapatadia  it look like you on top of this, can you create a pull request and I'll merge it?

**Comment by adityapatadia** [comment]
I can create PR but are you sure we should remove customisation and ajax code? What are your thoughts?

**Comment by excelwebzone** [comment]
I have been super busy with work, didn't have a chance to verify that it on the Google side.. maybe it would be good to actually leave it the way it is , incase they will modify the API. Make sense?

**Comment by adityapatadia** [comment]
okay cool. May be you can just add a line in readme to direct users about this recent change? Apart from that default implementation works fine.

**Comment by excelwebzone** [comment]
Thanks @adityapatadia
