### ISSUE TITLE
Support new google no-captcha recaptcha

### ISSUE THREAD

**Issue by gpapin** [excelwebzone/EWZRecaptchaBundle#40]
Any idea how to support the new google no-captcha recaptcha ?
I start to see it in few places and would be nice to add it's support in this bundle

http://googleonlinesecurity.blogspot.co.uk/2014/12/are-you-robot-introducing-no-captcha.html

**Comment by hmig** [comment]
It looks like there are two commits to address this issue: 

https://github.com/excelwebzone/EWZRecaptchaBundle/commit/3fa94a02e0cf77416eb2690d53dc797c9c736703
https://github.com/excelwebzone/EWZRecaptchaBundle/commit/2750f4864cd2dbfeba4e2461d835c6cfbd949296

@excelwebzone - any chance a new tag will be coming soon so we can get the update?

Thanks!

**Comment by hppycoder** [comment]
@excelwebzone - Could you setup a release with the following commits mentioned above? This would allow people to move to Recaptcha v2 which is a major improvement over v1.

**Comment by NicoLB** [comment]
**+1** - Upgrade to v2 would be much appreciated. Thanks!

**Comment by nocive** [comment]
:+1:

**Comment by hppycoder** [comment]
Any movement on having this be officially released? I believe it should be tagged 1.2.0 as it does add a new feature, and provides backwards compatibility. Thoughts @excelwebzone

**Comment by excelwebzone** [comment]
Sorry been super busy. Will create a new tag this weekend.

**Comment by hppycoder** [comment]
Thanks! We changed today to use dev-master. It's working well for us, seems stable

**Comment by excelwebzone** [comment]
Tag v.1.2.0 has been created!
