### ISSUE TITLE
Render and validate recaptcha when FormType and FormBuilder not used

### ISSUE THREAD

**Issue by NovikovViktor** [excelwebzone/EWZRecaptchaBundle#43]
Hello, I have a form, and for some reasons I cant use form type, or form builder to create it. So when in Twig template I pass `<form>` and script for recaptcha from EWZRecaptchaBundle doc, it renders captcha properly but not validate. So the question is, there is exist "bundle-way" to validate form, or I need to write peace of custom javascript ?

**Comment by lethak** [comment]
The bundle is optimized to work with a FormType/Builder/Validator combo.
In my point of view, there is no point using it if you do not plan to use a FormType

**Comment by excelwebzone** [comment]
@NovikovViktor  like @lethak says, this bundle uses the FormType/Builder/Validator combo, so as long as you follow the instructions you should be fine. You are always welcome to contribute any ideas you have and I will review them. Thanks.
