### ISSUE TITLE
Request to google with https

### ISSUE THREAD

**Issue by Chrysweel** [excelwebzone/EWZRecaptchaBundle#47]
Hello. I have the following error..

```
Mixed Content: The page at 'https://www.my-domain.net/register' was loaded over HTTPS, but requested an insecure script 'http://www.google.com/recaptcha/api/challenge?k=my_key'. This request has been blocked; the content must be served over HTTPS.
```
How can I to do a request to captcha https ?

Thanks

**Comment by lethak** [comment]
All the URL seems to be HTTPS
https://github.com/excelwebzone/EWZRecaptchaBundle/search?utf8=%E2%9C%93&q=www.google.com%2F

Are you using a recent version of the bundle ? I did not stumble upon this while implementing it on my project.

**Comment by Chrysweel** [comment]
Yes I think that I was a intern problem.

Close issue, thanks !
