### ISSUE TITLE
Use Recaptcha google

### ISSUE THREAD

**Issue by Chrysweel** [excelwebzone/EWZRecaptchaBundle#48]
Hello.

I use version:
>"excelwebzone/recaptcha-bundle" : "2.3.*@dev",

How can I use the version easy of captcha google ? 

>https://www.google.com/recaptcha/intro/index.html

I saw the documentation, but I dont know how do it ..
thanks in advance ! :)

**Comment by lethak** [comment]
You have to generate a new set of recaptcha key from google (they call them 'v2').
Only v2 keys will display the new version of reCaptcha

**Comment by Chrysweel** [comment]
ajá ok thanks @lethak .

I will try now ! If it work I will close the issue.

**Comment by Chrysweel** [comment]
@lethak I created a new key from 
>https://www.google.com/recaptcha/admin#list

But I can not choose nowhere v2 version... 0_0
I created a new key, and recaptcha version is the same..

I know that problem is with recaptcha google and not about this bundle... but I appreciate a help

**Comment by lethak** [comment]
Have you cleared the cache after changing the keys in your config ?
I have no more ideas about this.

By the way, you are not "choosing" the new version. If you create a new key, it will be V2 by default.
Look the details of your old keys from
> https://www.google.com/recaptcha/admin#list

It says they are v1, so, if nothing is displayed, it is v2.

**Comment by Chrysweel** [comment]
I have not idea... I am from Spain, maybe in spain is not available this recaptcha... I dont know.

If you want I close this issue... You say that with bundle no I have to configure nothing.. only to put the new key.... so the problem is not with bundle ..
I use the version 2.3.*@dev

**Comment by excelwebzone** [comment]
@Chrysweel I'm not sure how it works in Spain, but it should be the same, just follow the bundle instructions and you should be fine.
