### ISSUE TITLE
Never validate recaptcha field

### ISSUE THREAD

**Issue by raulggm** [excelwebzone/EWZRecaptchaBundle#55]
I'm using Symfony 2.7 and I'm trying to use this bundle (dev-master) in my registration form. I have followed the steps of documentation but it's not work, never validate the recaptcha field.

I've configured the bundle

```
ewz_recaptcha:
    public_key:  my_public_key
    private_key: my_private_key
    locale_key:  %kernel.default_locale%
```

I've added recaptcha in my class Register:

```
// ...
use EWZ\Bundle\RecaptchaBundle\Validator\Constraints as Recaptcha;

class Register
{
    // ...

    /**
     * @Recaptcha\IsTrue
     */
    public $recaptcha;

    // ...
}
```

and in my RegisterType:

```
// ...
class RegisterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // ...  
        ->add('recaptcha', 'ewz_recaptcha');
    }

    public function getName()
    {
        return 'register';
    }
}
```

and in my form template:

```
{# ... #}
{{ form_widget(form.recaptcha) }}
{# ... #}
```

When I submit the form, never show error message "This value is not a valid captcha." although I don't check it. Have I to do something in my controller when I get and valid the form submit?

Thanks.

**Comment by jekeyeke** [comment]
Hello!

I had the same problem and I solved it very simple: in my key secret, rewrited mine "-" and it works!
It was because I copied from web the key and the charset was different that the Symfony.

Hope it helps!

**Comment by excelwebzone** [comment]
Thanks @jekeyeke
