### ISSUE TITLE
Fallback to setDefaultOptions if Symfony version is 2.6 or less

### ISSUE THREAD

**Issue by ste93cry** [excelwebzone/EWZRecaptchaBundle#64]
The form type works only with Symfony 2.7+ due to the fact that you're using `configureOptions` method only. Like other bundles, `setDefaultOptions` should still be available and just call `configureOptions` so that both the versions of Symfony works.

**Comment by ste93cry** [comment]
@excelwebzone any news about when this can be merged?

**Comment by excelwebzone** [comment]
I have created a new branch for 2.6
