### ISSUE TITLE
Add Symfony3 support

### ISSUE THREAD

**Issue by prashantsohani** [excelwebzone/EWZRecaptchaBundle#76]

**Comment by hlecorche** [comment]
+1

**Comment by excelwebzone** [comment]
Quick look over v3, I found the following changes:
* The `getBlockPrefix()` method was added to the `FormTypeInterface` in replacement of the `getName()` method which has been has been removed.
* The `configureOptions()` method was added to the `FormTypeInterface` in replacement of the `setDefaultOptions()` method which has been removed.
* The method `AbstractType::setDefaultOptions(OptionsResolverInterface $resolver)` and `AbstractTypeExtension::setDefaultOptions(OptionsResolverInterface $resolver)` have been renamed. You should use `AbstractType::configureOptions(OptionsResolver $resolver)` and `AbstractTypeExtension::configureOptions(OptionsResolver $resolver)` instead.

**Comment by MJBGO** [comment]
I'm actually updating the bundle on my side, I'll do a pull request when it's all done ;)
