### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by tristanbes** [excelwebzone/EWZRecaptchaBundle#78]
Hi,

Can you tag a new release so I can upgrade my project to >= Symfony 2.8. Currently relies on Frameworkbundle 2.0 when Symfony2.8 ships 3.* of framework bundle.

Thanks

**Comment by excelwebzone** [comment]
Just made v1.4.2.. enjoy :-)

**Comment by tristanbes** [comment]
Thanks!
Le 7 janv. 2016 16:58, "Michael H. Arieli" <notifications@github.com> a
écrit :

**Comment by ByScripts** [comment]
I think you should follow [SemVer](http://semver.org/) convention.

1.4.1 was Symfony 2.4 and 1.4.2 is Symfony 3.0 and break everything.
