### ISSUE TITLE
[Feature Request] trusted_roles option

### ISSUE THREAD

**Issue by slmcncb** [excelwebzone/EWZRecaptchaBundle#86]
How can I disable the captcha at admin page?

I'm using [EasyAdminBundle](https://github.com/javiereguiluz/EasyAdminBundle).

**Comment by slmcncb** [comment]
I solved the problem. 

@excelwebzone I added trusted_roles option.

Notice: I'm having problems sending pull request (v1.4.1).

**service.xml > ewz_recaptcha.validator.true**
```xml
...
<argument type="service" id="security.authorization_checker" />
<argument>%ewz_recaptcha.trusted_roles%</argument>
...
```

**DependencyInjection\Configuration.php > getConfigTreeBuilder()**
```php
...
$rootNode
            ->children()
                ->scalarNode('public_key')->isRequired()->end()
                ->scalarNode('private_key')->isRequired()->end()
                ->booleanNode('enabled')->defaultTrue()->end()
                ->booleanNode('ajax')->defaultFalse()->end()
                ->scalarNode('locale_key')->defaultValue('%kernel.default_locale%')->end()
                ->arrayNode('trusted_roles')
                    ->prototype('scalar')
                    ->end()
                ->end()
            ->end()
        ;
...
```

**Validator\Constraints\IsTrueValidator.php**
```php
    /**
     * Authorization Checker
     *
     * @var AuthorizationChecker
     */
    protected $authorizationChecker;

    /**
     * Trusted Roles
     *
     * @var Array
     */
    protected $trusted_roles;
```

**Validator\Constraints\IsTrueValidator.php > __construct()**
```php
public function __construct($enabled, $privateKey, RequestStack $requestStack, array $httpProxy = array(), AuthorizationChecker $authorizationChecker, $trusted_roles)
    {
        $this->enabled = $enabled;
        $this->privateKey = $privateKey;
        $this->requestStack = $requestStack;
        $this->httpProxy = $httpProxy;
        $this->authorizationChecker = $authorizationChecker;
        $this->trusted_roles = $trusted_roles;
    }
```

**Validator\Constraints\IsTrueValidator.php > validate()**
```php
...
        // if recaptcha is disabled, always valid
        if (!$this->enabled) {
            return true;
        }

        if ($this->authorizationChecker->isGranted($this->trusted_roles)) {
            return true;
        }
...
```

**Comment by julienpillias** [comment]
Any chance to have this in the main repo ?

**Comment by julienpillias** [comment]
@excelwebzone ?

**Comment by excelwebzone** [comment]
You can go ahead and make a PR, and I will review it when I have some time. Thank.

**Comment by julienpillias** [comment]
trying to PR from PHPStorm (first PR for me on github "public"), and having this error : 

Can't Create Pull Request
			Push failed:
			unable to access 'https://github.com/excelwebzone/EWZRecaptchaBundle.git/': The requested URL returned error: 403

Any idea ?

**Comment by excelwebzone** [comment]
Use https://desktop.github.com/ much better.

**Comment by julienpillias** [comment]
Tried with desktop github, same with 2 accounts (one professionnal, and one personnal) : 

Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository.

Maybe because of my custom branch ? (features/trustedRoles)

**Comment by excelwebzone** [comment]
Right, you have to clone it to your account first, then make changes, commit, and from your GitHub account  you would be able to create a "pull request".

**Comment by julienpillias** [comment]
TY.
PR is ready : https://github.com/excelwebzone/EWZRecaptchaBundle/pull/192

**Comment by excelwebzone** [comment]
Thanks. I will review it and if all good, I will merge later today.
