### ISSUE TITLE
Allow symfony 2.8 OR 3.0

### ISSUE THREAD

**Issue by mablae** [excelwebzone/EWZRecaptchaBundle#87]
I cannot use the latest version of the bundle, because the Bundle requires Symfony3 now. 
But it should be like `~2.8|~3.0` - I think it wont break anything, just maybe a few deprecation warnings. 

Would be awsome to be able to use the language overrride introduced in v.1.4.2. 

Should I submit a PR for it?

**Comment by excelwebzone** [comment]
I just merged #88

**Comment by mablae** [comment]
Nice! I was relying on my feature branch in production, without any updates since then. Now can remove the alias. Thank you.
